### ISSUE TITLE
Back-end-Tlax-room

### ISSUE THREAD

**Issue by Jaimer117** [SistemasTecTlaxiaco/practica-back-end-tlax-room#2]
[PRACTICA BACK-END tlaxroom.pdf](https://github.com/SistemasTecTlaxiaco/practica-back-end-tlax-room/files/6549298/PRACTICA.BACK-END.tlaxroom.pdf)

**Comment by Nancy2050** [comment]
Calificacion: 30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
